// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://itdkfzzajyxfofnrgkqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_ntiOm2gHCioQGX7oVKaOwQ_861OGJjQ";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
